# Generated by Django 4.2.6 on 2023-12-16 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_atividade_professor_turma_delete_carro_delete_moto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alu_nome', models.CharField(max_length=255)),
                ('alu_email', models.EmailField(max_length=254, unique=True)),
                ('alu_senha', models.IntegerField()),
                ('prof_foto', models.ImageField(default='static/images/sem_foto.jpg', upload_to='fotos_professores/')),
                ('alu_num_matricula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AutoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_nome', models.CharField(max_length=255)),
                ('auto_peso', models.FloatField()),
                ('auto_id_alu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aval_nome', models.CharField(max_length=255)),
                ('aval_valortotal', models.FloatField()),
                ('aval_data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacoesAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aval_alun_nota', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crit_nome', models.CharField(max_length=255)),
                ('crit_descricao', models.CharField(max_length=1024)),
                ('crit_peso', models.FloatField()),
                ('crit_aval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_nome', models.CharField(max_length=255)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_alu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aluno')),
                ('user_nome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_nome', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='turma_turno',
            new_name='tur_turno',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='nome_professor',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='aluno_quantidade',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='atividades',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='numero_sala_turma',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='turma_codigo',
        ),
        migrations.AddField(
            model_name='professor',
            name='prof_foto',
            field=models.ImageField(default='static/images/sem_foto.jpg', upload_to='fotos_professores/'),
        ),
        migrations.AddField(
            model_name='professor',
            name='prof_nome',
            field=models.CharField(default='Professor sem nome', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='prof_sobrenome',
            field=models.CharField(default='Professor sem sobrenome', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='prof_telefone',
            field=models.CharField(default='00000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='tur_nome',
            field=models.CharField(default='Turma sem nome', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='tur_sala',
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_prof_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_senha',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_senha', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='prof_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
        migrations.AddField(
            model_name='avaliacoesaluno',
            name='aval_alun_crit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.criterio'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='aval_disc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='aval_prof_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='aval_tur_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma'),
        ),
    ]
